### ISSUE TITLE
ISSUES: componentDidMount for server calls

### ISSUE THREAD

**Issue by alexanderturuta** [dinasergienko/SpotifySearch#3]
https://daveceddia.com/where-fetch-data-componentwillmount-vs-componentdidmount/

componentDidMount is a better place for server calls

![image](https://user-images.githubusercontent.com/2150198/37770882-e55ea158-2de6-11e8-8398-995a671103f2.png)

**Comment by dinasergiyenko** [comment]
[Link](https://github.com/dinasergienko/SpotifySearch/commit/8ba3c147c2fb30e07917a6fa0ea62757a168bdcc) to the commit
