### ISSUE TITLE
ISSUES: Move track layout to component

### ISSUE THREAD

**Issue by alexanderturuta** [dinasergienko/SpotifySearch#9]
![image](https://user-images.githubusercontent.com/2150198/37773456-bbf11adc-2dee-11e8-952b-db9859e1ff96.png)

**Comment by dinasergiyenko** [comment]
[Link](https://github.com/dinasergienko/SpotifySearch/commit/fd5e37d16132b9ba263b1f4a585e2dcb73239d59) to the commit
